

CREATE TABLE Member (
    name   VARCHAR2(20) NOT NULL,
    userid VARCHAR2(20) PRIMARY KEY,
    pwd    VARCHAR2(20) NOT NULL,
    phone  CHAR(20),
    email  VARCHAR2(20)
);


SELECT * FROM Member;

SELECT * FROM Reservation;
DELETE FROM Reservation;
DROP TABLE Reservation CASCADE CONSTRAINTS;




CREATE TABLE RESERVATION (
    RES_ID        NUMBER PRIMARY KEY,
    USER_ID       VARCHAR2(50),
    TRIP_TYPE     VARCHAR2(10), -- ONE_WAY or ROUND
    ORIGIN        VARCHAR2(10),
    DESTINATION   VARCHAR2(10),
    DEPART_DATE   DATE,
    RETURN_DATE   DATE,
    ADULT_COUNT   NUMBER,
    CHILD_COUNT   NUMBER,
    INFANT_COUNT  NUMBER,
    CREATED_AT    DATE DEFAULT SYSDATE
);
DROP SEQUENCE RESERVATION_SEQ;


CREATE SEQUENCE RESERVATION_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;
